spring.application.name=PetFriendsAlmoxarifado
server.port=8081

# POSTGRES DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/almoxarifado
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

#RABBITMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# LOGGING
logging.level.org.hibernate=OFF
logging.level.org.springframework.orm.jpa=OFF
logging.level.com.zaxxer.hikari=OFF
logging.level.org.springframework.jdbc=OFF

logging.level.root=ERROR
logging.level.com.infnet=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [${spring.application.name}] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [${spring.application.name}] %logger{36} - %msg%n
logging.file.name=logs/petfriends.log

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.prometheus.metrics.export.enabled=true